//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bank_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTable
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string PhoneNumber { get; set; }
        public string IDNumber { get; set; }
        public string BankCardNumber { get; set; }
        public string Operator { get; set; }
        public double Money { get; set; }
        public string DepositType { get; set; }
    }
}
