//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bank_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdministratorTable
    {
        public string AdiminName { get; set; }
        public string AdminPasswd { get; set; }
        public string AdminPhoneNumber { get; set; }
        public string AdminSex { get; set; }
        public string AdminID { get; set; }
        public double AdminSalary { get; set; }
    }
}
