//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace bank_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyInfo
    {
        public string Id { get; set; }
        public string AccountNo { get; set; }
        public System.DateTime DealDate { get; set; }
        public string DealType { get; set; }
        public double DealMoney { get; set; }
        public double Balance { get; set; }
    }
}
